### ISSUE TITLE
Unable to edit metadata

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/jupiter#1872] opened 2020-09-14 19:46 UTC
Reporting on behalf of a staff member trying to edit a record (note keywords were requested from the authors of this item):

"I have a question regarding depositing an ebook, the initial problem with depositing the Ebook was solved by Matt however, I have the same issue with adding keywords.
That is what I am working on:
https://era.library.ualberta.ca/items/9bbcd0ba-9a7f-4622-a361-073435439350

Those are the keywords that I am trying to enter:
Athabasca oil sands, bitumen recovery, bitumen aqueous extraction, bitumen flotation, bitumen froth treatment, demulsification, hydrotransport pipeline, bitumen – surface properties, tailings management."

**Comment by mbarnett** [comment] 2020-09-18 20:34
Same root cause as #1867 (and probably some of the other reports you've got in Helpdesk, too). 

Ultimately I can individually fix all of these by hand, each time the user wants to edit the metadata (and I'll try to spend an afternoon in the VPN soon cleaning these up), but the root-cause issue here is Fedora, so I think our time is better spent trying to get this fixed across the board for everybody rather than getting bogged down too much in endlessly fighting the symptoms and delaying progress on the cure.

**Comment by mbarnett** [comment] 2020-09-24 16:52
Closed via same fix as #1867

**Closed by mbarnett** 2020-09-24 16:52 UTC
