### ISSUE TITLE
Batch ingest Ball Collection

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#922] opened 2018-11-13 21:20 UTC
**Brief description of the batch**
This is an image collection from Allan Ball. 

**Manifest**
Original manifest at:
https://drive.google.com/open?id=1AlflT-SSNPIoLN-GAjlm37-dCzigHd5Q-8fWGwq0SJ8
Need an updated manifest for batch ingest. 

**Batch files**
https://drive.google.com/open?id=1_0nUIW_uYF9Mae96o7xvse9C9azJ18C0

**Additional notes**

**Comment by dancockcroft** [comment] 2018-11-13 23:05
@weiweishi New manifest for ingest here:
https://drive.google.com/drive/folders/1AlkCXra4EfwzYsnUv5mzPS0RsWEav38y?ogsrc=32

**Comment by weiweishi** [comment] 2018-11-13 23:08
thank you very much Dan. Will be working on this batch and will let you
know if there's any issue. Will also attach the final report to this ticket
once the batch ingest is completed.

Weiwei


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by dancockcroft** [comment] 2018-11-13 23:13
Something to follow up on if there are any problems: I don't think it had any effect on the manifest, but the script did throw up an error stating that it could only validate 500 items at a time.

**Comment by weiweishi** [comment] 2018-12-05 20:10
@leahvanderjagt @dancockcroft all of the images are under: Attribution-NonCommerical-NoDerivs 2.0 International. Is this the CC license version these images are under? We might have to do some code changes to allow this version of cc license to be used.

**Comment by weiweishi** [comment] 2018-12-06 18:13
additional question @dancockcroft, the collection ID used in the manifest doesn't exist. And the community this collection is under is: https://era.library.ualberta.ca/communities/4ab5150d-2606-4a49-b400-2defbd6ce306. Documents of Contemporary War, which doesn't seem to make a lot of sense for this image collection. Could you please check the proper community/collection IDs for this batch? Thanks!

**Comment by dancockcroft** [comment] 2018-12-06 19:18
@weiweishi The documentation accompanying the investigation states "License: Required. This will be https://creativecommons.org/licenses/by-nc-nd/2.0/ca/ for all. We will add this on ingest." I think we'll have to use it.

**Comment by sfarnel** [comment] 2018-12-07 02:15
HI @weiweishi and @dancockcroft Hope you don't mind me jumping in here but I worked with Sean and Allan (and his students) on the metadata for this. The community is 4ab5150d-2606-4a49-b400-2defbd6ce306 and the collection is 95099a9e-214d-4974-bdbd-1b63fb8e625c Re: the license, we had discussions and Allan wanted attribution, non-commercial, no derivatives and was happy to go with the latest version. The mention of 2.0 in the document is an error that should have been corrected. So you can go with version 4.0. There are also descriptions of the community and collection in the document that Allan wanted added. Hope this helps :)

**Comment by weiweishi** [comment] 2018-12-07 17:19
Thank you Sharon. This is very helpful and great to hear that current
version of the CC license would work for this collection. This allows us to
move the ingest forward, without having to wait for a deployment/code
change to enable the use of the older version of the license. I will
proceed with the batch ingest based on the information you provided.



*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by weiweishi** [comment] 2019-01-04 22:56
@dancockcroft It seems some of the files are not in the directory, or the filename might be mismatching with the information provided in the manifest? 

Here is a snippet of some of the failed ingest in this collection. 
```
[2018-12-07 23:15:19] ITEM 30: Starting ingest of an item...
[2018-12-07 23:15:21] ITEM 30: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_035.jpg
[2018-12-07 23:15:21] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:21] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_035.jpg
[2018-12-07 23:15:21] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:21] ITEM 31: Starting ingest of an item...
[2018-12-07 23:15:24] ITEM 31: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_036.jpg
[2018-12-07 23:15:24] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:24] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_036.jpg
[2018-12-07 23:15:24] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:24] ITEM 32: Starting ingest of an item...
[2018-12-07 23:15:26] ITEM 32: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_037.jpg
[2018-12-07 23:15:26] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:26] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_037.jpg
[2018-12-07 23:15:26] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:26] ITEM 33: Starting ingest of an item...
[2018-12-07 23:15:28] ITEM 33: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_038.jpg
[2018-12-07 23:15:28] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:28] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_038.jpg
[2018-12-07 23:15:28] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:28] ITEM 34: Starting ingest of an item...
[2018-12-07 23:15:31] ITEM 34: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_039.jpg
[2018-12-07 23:15:31] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:31] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_039.jpg
[2018-12-07 23:15:31] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:31] ITEM 35: Starting ingest of an item...
[2018-12-07 23:15:33] ITEM 35: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_040.jpg
[2018-12-07 23:15:33] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:33] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_040.jpg
[2018-12-07 23:15:33] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:33] ITEM 36: Starting ingest of an item...
[2018-12-07 23:15:35] ITEM 36: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_041.jpg
[2018-12-07 23:15:35] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:35] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_041.jpg
[2018-12-07 23:15:35] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:35] ITEM 37: Starting ingest of an item...
[2018-12-07 23:15:38] ITEM 37: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_042.jpg
[2018-12-07 23:15:38] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:38] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_042.jpg
[2018-12-07 23:15:38] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:38] ITEM 38: Starting ingest of an item...
[2018-12-07 23:15:40] ITEM 38: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_043.jpg
[2018-12-07 23:15:40] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:40] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_043.jpg
[2018-12-07 23:15:40] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:40] ITEM 39: Starting ingest of an item...
[2018-12-07 23:15:42] ITEM 39: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_044.jpg
[2018-12-07 23:15:42] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:42] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_044.jpg
[2018-12-07 23:15:42] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:42] ITEM 40: Starting ingest of an item...
[2018-12-07 23:15:45] ITEM 40: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_045.jpg
[2018-12-07 23:15:45] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:45] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_045.jpg
[2018-12-07 23:15:45] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:45] ITEM 41: Starting ingest of an item...
[2018-12-07 23:15:47] ITEM 41: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_046.jpg
[2018-12-07 23:15:47] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:47] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_046.jpg
[2018-12-07 23:15:47] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:47] ITEM 42: Starting ingest of an item...
[2018-12-07 23:15:50] ITEM 42: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_047.jpg
[2018-12-07 23:15:50] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:50] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_047.jpg
[2018-12-07 23:15:50] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:50] ITEM 43: Starting ingest of an item...
[2018-12-07 23:15:52] ITEM 43: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_048.jpg
[2018-12-07 23:15:52] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:52] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_048.jpg
[2018-12-07 23:15:52] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:52] ITEM 44: Starting ingest of an item...
[2018-12-07 23:15:54] ITEM 44: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_049.jpg
[2018-12-07 23:15:54] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:54] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_049.jpg
[2018-12-07 23:15:54] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
[2018-12-07 23:15:54] ITEM 45: Starting ingest of an item...
[2018-12-07 23:15:57] ITEM 45: Starting ingest of file for item...
/home/weiweis/batchBallFiles/2007_06_04_050.jpg
[2018-12-07 23:15:57] ERROR: Ingest of item failed! The following error occured:
[2018-12-07 23:15:57] EXCEPTION: No such file or directory @ rb_sysopen - /home/weiweis/batchBallFiles/2007_06_04_050.jpg
[2018-12-07 23:15:57] WARNING: Please be careful with rerunning batch ingest! Duplication of items may happen if previous items were successfully deposited.
```

**Comment by dancockcroft** [comment] 2019-01-08 17:52
@weiweishi In 'case' this is the problem, I've normalized the case of the extensions here: https://drive.google.com/drive/folders/1o-4l1FA-PR8OcKA7DJiLmHVpuyaUt43L?ogsrc=32

**Comment by seanluyk** [comment] 2019-08-29 16:29
@weiweishi, just checking in on the status of this batch and if there's anything on our end we can do on our end?

**Comment by dancockcroft** [comment] 2019-08-29 17:46
@weiweishi @seanluyk 
After another unsuccessful test upload, I ran the 1200 filenames against each other to find discrepancies. This is what I found:

''2007_06_04_004.jpg'' was incorrectly named ''2007_06_06_004.jpg''. This has been fixed.

**Comment by weiweishi** [comment] 2019-08-29 17:56
Thank you very much Dan. Will run the batch ASAP.


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by dancockcroft** [comment] 2019-08-29 18:03
@weiweishi Updated comment.

**Comment by seanluyk** [comment] 2019-08-29 19:07
@weiweishi 

Upon closer inspection, it does look like a large number of objects, including their files, were ingested, so I don't think this should be wiped out and completely redone, unless that's the only way to fix the issue

**Comment by dancockcroft** [comment] 2019-08-29 19:15
@seanluyk @weiweishi 

It looks like a lot of the records were created, but the images never made it through. Might be worth a fresh start?

https://era.library.ualberta.ca/communities/4ab5150d-2606-4a49-b400-2defbd6ce306/collections/95099a9e-214d-4974-bdbd-1b63fb8e625c

**Comment by seanluyk** [comment] 2019-08-29 19:27
@dancockcroft thanks for updating the manifest and for your attention to this! I'm wondering (and @weiweishi can confirm) is whether or not it's more advisable to delete/re-ingest just the objects that don't contain files, and keep the ones that are complete, or if the easiest thing to do is start fresh with this one

**Comment by seanluyk** [comment] 2019-09-06 17:45
@weiweishi I was wondering where we landed on this one. Is the best course of action to re-ingest the entire collection en masse, or just the object with missing image files? I'm not as familiar with what's possible in Jupiter in terms of batch update, etc.

**Comment by weiweishi** [comment] 2019-09-12 05:54
Completed. Deposit report is available here:

[2019_09_10_23_23_48.txt](https://github.com/ualbertalib/jupiter/files/3603912/2019_09_10_23_23_48.txt)

**Closed** 2019-09-16 22:19 UTC
Labels: batch ingest request
