### ISSUE TITLE
[Jupiter] Year limiter does not reflect existing collection parameter

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#899] opened 2018-10-26 18:51 UTC
When I use the year limiter within a collection, it limits across all of ERA rather than the collection I am already in.

1. Go to any collection (e.g., Theses and Dissertations)
2. On the year limiter select 2015-2018
3. Click Limit
4. The items in the results list come from all collections in ERA

When using this limiter it should only return items in the current collection that have that date range.

Windows 7 Enterprise
Firefox Quantum 60.3.0

**Comment by pbinkley** [comment] 2018-11-19 20:50
Note the url for a year limitation goes to the main search, and has no facet for the collection: https://era.library.ualberta.ca/search?utf8=%E2%9C%93&ranges%5Bsort_year_isi%5D%5Bbegin%5D=2015&ranges%5Bsort_year_isi%5D%5Bend%5D=2018&search=&direction=

But clicking a subject facet in a collection uses a facet param on the collection url: https://era.library.ualberta.ca/communities/db9a4e71-f809-4385-a274-048f28eb6814/collections/f42f3da6-00c3-4581-b785-63725c33c7ce?facets%5Ball_subjects_sim%5D%5B%5D=Canada

**Comment by sfarnel** [comment] 2019-01-08 17:30
Apologies but it seems this problem has come back.

Theses and dissertations collection: https://era.library.ualberta.ca/communities/db9a4e71-f809-4385-a274-048f28eb6814/collections/f42f3da6-00c3-4581-b785-63725c33c7ce

When I limit to 2011-2015: https://era.library.ualberta.ca/search?utf8=%E2%9C%93&ranges%5Bsort_year_isi%5D%5Bbegin%5D=2011&ranges%5Bsort_year_isi%5D%5Bend%5D=2015&search=&direction=

**Comment by sfarnel** [comment] 2019-01-08 18:34
Thanks @murny

**Comment by murny** [comment] 2019-01-09 17:57
So the problem is the bug fix hasn't been deployed out to production yet! (I thought i was going crazy :sweat_smile: )

We are probably running 1.2.6 in production as of writing this (admin dashboard says 1.2.3 so we definitely don't have the latest version in production as we updated this version number in 1.2.7 here on Dec 3: https://github.com/ualbertalib/jupiter/commit/e047c0aca2af60f741d93b525133a1c2d01aa368)? The latest release v1.2.7 has this fix in it. So once we deploy this, I'll update/close this ticket.

Leaving this ticket open until this is in production

(Thanks @pgwillia for the suggestion!)

**Comment by sfarnel** [comment] 2019-01-09 20:17
Cool!

**Comment by mbarnett** [comment] 2020-04-24 20:36
Production is now running 1.2.19, so I'm closing this because I assume this is long since fixed in Production. Please feel free to re-open if I'm wrong or this is still an issue.

**Closed by mbarnett** 2020-04-24 20:36 UTC
Labels: bug
